name: Publish release

on:
  release:
    types: [published]

jobs:
  send_message_job:
    runs-on: ubuntu-latest
    name: Publish release
    steps:
      - name: Send a message to Microsoft Teams
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.TEAMS_WEBHOOK_URL}}
          title: New release ${{ github.event.release.name }} from ${{ github.event.repository.name }}
          summary: A new release (${{ github.event.release.tag_name }}) has been created
          text: ${{ github.event.release.body }}
          theme_color: 0000FF
          actions: '[{"@type": "OpenUri", "name": "View release", "targets": [{ "os": "default", "uri": "${{ github.event.release.html_url }}"}]}]'

      - name: Send a message to Microsoft Outlook
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.OUTLOOK_WEBHOOK_URL}}
          title: New release ${{ github.event.release.name }} from ${{ github.event.repository.name }}
          summary: A new release (${{ github.event.release.tag_name }}) has been created
          text: ${{ github.event.release.body }}
          theme_color: 0000FF
          actions: '[{"@type": "OpenUri", "name": "View release", "targets": [{ "os": "default", "uri": "${{ github.event.release.html_url }}"}]}]'